@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":SpendNSplitParser" as SpendNSplitParser LOGIC_COLOR
participant ":AddPersonCommandParser" as AddPersonCommandParser LOGIC_COLOR
participant ":Name" as Name LOGIC_COLOR
participant ":Person" as Person LOGIC_COLOR
participant "ap:AddPersonCommand" as AddPersonCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("addPerson n=name")
activate LogicManager

LogicManager -> Model : getCommandMap()
activate Model
Model --> LogicManager : commandMap
deactivate Model

LogicManager -> SpendNSplitParser : parseCommand("addPerson n=name", commandMap)
activate SpendNSplitParser

create AddPersonCommandParser
SpendNSplitParser -> AddPersonCommandParser
activate AddPersonCommandParser

AddPersonCommandParser --> SpendNSplitParser
deactivate AddPersonCommandParser

SpendNSplitParser -> AddPersonCommandParser : parse("n=name")
activate AddPersonCommandParser

create Name
AddPersonCommandParser -> Name
activate Name
Name --> AddPersonCommandParser
deactivate Name

create Person
AddPersonCommandParser -> Person
activate Person
Person --> AddPersonCommandParser
deactivate Person

create AddPersonCommand
AddPersonCommandParser -> AddPersonCommand
activate AddPersonCommand

AddPersonCommand --> AddPersonCommandParser : ap
deactivate AddPersonCommand

AddPersonCommandParser --> SpendNSplitParser : ap
deactivate AddPersonCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddPersonCommandParser -[hidden]-> SpendNSplitParser
destroy AddPersonCommandParser

SpendNSplitParser --> LogicManager : ap
deactivate SpendNSplitParser

LogicManager -> AddPersonCommand : execute()
activate AddPersonCommand

AddPersonCommand -> Model : addPerson(newPerson)
activate Model

Model --> AddPersonCommand
deactivate Model

create CommandResult
AddPersonCommand -> CommandResult
activate CommandResult

CommandResult --> AddPersonCommand
deactivate CommandResult

AddPersonCommand --> LogicManager : result
deactivate AddPersonCommand

[<--LogicManager
deactivate LogicManager
@enduml
