@startuml
!pragma useVerticalIf on
start
:User enters addPerson command;
if () then ([Person name is not provided])
  :Throw exception;
  stop
([else]) elseif () then ([Some provided fields are invalid])
  :Throw exception;
  stop
([else]) elseif () then ([Person name is a reserved word])
  :Throw exception;
  stop
([else]) elseif () then ([Person already exists in the person list])
  :Throw exception;
  stop
else ([else])
  :Add person to the person list;
endif
stop
@enduml
