@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":SpendNSplit" as SpendNSplit MODEL_COLOR
participant ":UniquePersonList" as UniquePersonList MODEL_COLOR
participant ":UniqueTransactionList" as UniqueTransactionList MODEL_COLOR
participant ":Transaction" as Transaction MODEL_COLOR
end box

mainframe sd delete person

Model -> SpendNSplit : deletePerson(personToDelete)
activate SpendNSplit

SpendNSplit -> UniquePersonList : remove(personToDelete)

SpendNSplit -> UniqueTransactionList : deletePerson(personToDeleteName, allPersonNames)
activate UniqueTransactionList

loop for each transaction
    UniqueTransactionList -> Transaction : removePerson(personToDeleteName)
    activate Transaction

    Transaction --> UniqueTransactionList : updatedTransaction
    deactivate Transaction

    alt #LightBlue updatedTransaction is valid
        UniqueTransactionList -> UniqueTransactionList : set transaction to updatedTransaction
    else #Pink
        UniqueTransactionList -> UniqueTransactionList : remove transaction
    end
end

UniqueTransactionList --> SpendNSplit
deactivate UniqueTransactionList

SpendNSplit -> SpendNSplit : sortPersons()

SpendNSplit --> Model
deactivate SpendNSplit
@enduml
