@startuml
!pragma useVerticalIf on
start
:User enters listTransaction command;
if () then ([Command format is invalid])
  :Throw exception;
  stop
else ([else])
  :Filter the transaction list;
endif
stop
@enduml
