@startuml
!pragma useVerticalIf on
start
:User enters setShorthand command;
if () then ([Command format is invalid])
  :Throw exception;
  stop
([else]) elseif () then ([Original command does not exist])
  :Throw exception;
  stop
([else]) elseif () then ([Shorthand is an original command])
  :Throw exception;
  stop
([else]) elseif () then ([Shorthand already in use by another command])
  :Throw exception;
  stop
endif
if () then ([Original command has a shorthand])
  :Replace old shorthand with new shorthand;
else ([else])
  :Add new shorthand to original command;
endif
stop
@enduml